### PR TITLE
add eight models

### PR DESCRIPTION
**Pull request by xzzWZY**

### CODE REVIEW

**Comment by jaywonchung** [comment]
I vaguely remember you telling me that some of the existing model results were incomplete. Were they actually complete?

**Comment by xzzWZY** [comment]
ooh, I forgot to change vicuna-13B and camel-13B to complete data, wait for a while(sorry

**Comment by jaywonchung** [comment]
Thanks. Since you'll have a script for averaging (please add that to the master branch), it'll make sense to recompute everything just in case.

**Comment by xzzWZY** [comment]
I replace the incomplete data with complete ones now

**Comment by jaywonchung** [comment]
Is this all good to now? You can request/re-request reviews to signal collaborators to tell them you think it's all good to go.

**Comment by xzzWZY** [comment]
I think so, there's maybe only one problem, that is I lost running ouput for vicuna-7B (quite sorry for miss deleting while checking maybe yesterday?), and I check all the other models, the output generate from previous regex match is the same as json.load and then read data, so I just remain the data for vicuna-7B as original, and I'm running it again in ampere01, cuda 00, and I think the data is all good(

**Comment by jaywonchung** [comment]
I see. Please let me know when it finishes. It's best if we release numbers that are all backed by an existing benchmark.json file. I'll merge this for now. Thanks a lot for the great work!

**Review by jaywonchung — APPROVED** [review]

**Pull request merged**
