### PR TITLE
add compute script

### PR DESCRIPTION
**Pull request by xzzWZY**
this script only compute average for four models, but can be easily extended to 20 models

### CODE REVIEW

**Comment by jaywonchung** [comment]
You should use the json built-in module to read json files, instead of parsing it manually with regex. That's error prone and I don't trust manually parsed json results. Please rewrite the json reading part and re-compute the metrics.

**Comment by jaywonchung** [comment]
Also don't manually read model names with the input built-in function. Use os.listdir("data/chat") to automate.

**Comment by xzzWZY** [comment]
okkkk, get it

**Comment by xzzWZY** [comment]
I‘ve changed to os.listdir and use json build-in module, and the origin data is all right(both number of query and value)

**Review by jaywonchung — APPROVED** [review]
LGTM. Thank you for your work!

**Pull request merged**
