### PR TITLE
Improve Gradio WebUI

### PR DESCRIPTION
**Pull request by jaywonchung**
I've made some aesthetics/robustness/quality-of-life improvements to `app.py` and bumped the version of `gradio` to the latest one.

Non-devs -- run it like this:

```sh
git clone git@github.com:ml-energy/leaderboard.git
cd leaderboard
git checkout jw-improve-gradio
pip install -r requirements.txt  # Assuming you have your virtual environment on
python app.py
```

### CODE REVIEW

**Comment by jaywonchung** [comment]
I've made the live link's benchmark data is up to date to #4, and can be considered the release candidate. @mosharaf @AmberLJC Please take a look.

**Comment by AmberLJC** [comment]
Just found a small problem that the figure is a bit crowded because of the name. We should put the version `-v12-Eng98%-Other2%-20230521-ctx8192.pth` in another tab
image

**Comment by jaywonchung** [comment]
Thanks for pointing out. There are other long names, too, like OpenAssistant models. I'll also put model nicknames in `models.json`.

**Comment by jaywonchung** [comment]
@AmberLJC Alright, that was an incredible amount of suffering to get nickname + making model names anchors work. Please take another look.

**Comment by AmberLJC** [comment]
just a small question; the `clear` button under `add to table` does not intend to remove the added column?

**Comment by jaywonchung** [comment]
You're right. The intention is just to clear the 'added' message and what the user put into the two input boxes. If the user wants to clear custom columns, refreshing is probably a faster way. Refreshing will clear everything because I wrapped the TableManage in `gr.State`. Without that, custom columns will persist across every user. https://gradio.app/state-in-blocks/

**Comment by jaywonchung** [comment]
I didn't implement removing columns individually, because I can't easily put X buttons *inside* the table header cells. Having a separate input box for the name of the column to remove can be a viable way, but I think it'll get ugly without increasing the users' quality of life that much.

**Comment by AmberLJC** [comment]
Everything else looks good to me! Let wait for @mosharaf comments

**Comment by jaywonchung** [comment]
- [ ] Add more details in the `About` tab about how the numbers were obtained. => @jaywonchung 

@AmberLJC Are there more TODOs you can thing of?

**Comment by mosharaf** [comment]
How do I see it from a phone? Any URL?

**Comment by AmberLJC** [comment]
https://8064ba372b6b687627.gradio.live/
check this

**Comment by jaywonchung** [comment]
https://311a4e9fb0b9339d7c.gradio.live
This URL is a proxy to an instance of the app running on my laptop (which I won't keep alive forever). If you're going to look at it later, ping me over Teams or refer to the instructions on the PR description.

**Comment by jaywonchung** [comment]
JaeWonGPT is apparently much more energy-inefficient than AmberGPT 😁

**Comment by AmberLJC** [comment]
> * [ ]  Add more details in the `About` tab about how the numbers were obtained. => @jaywonchung
> 
> @AmberLJC Are there more TODOs you can thing of?

 * [ ]  Fill the empty score entries
 * [ ] Allow user to submit their model
 * [ ] Further reduce the length of model name

**Comment by jaywonchung** [comment]
Yeah. I should put a list of TODOs/milestones and current limitations in the About page.

**Comment by mosharaf** [comment]
Neither of the links open. I'll try out later when I'm on a laptop.

**Comment by jaywonchung** [comment]
Actually, let's just merge. Then you can look at our HF Space here: https://huggingface.co/spaces/symbioticlab/ml-energy-leaderboard?__theme=light

**Comment by mosharaf** [comment]
I don't see anything in that space? Do I have to be logged in?

**Comment by jaywonchung** [comment]
Yes, you have to be logged in. It's currently private.

**Pull request merged**
