### PR TITLE
More info in app and about page

### PR DESCRIPTION
**Pull request by jaywonchung**
I added some text in the Leaderboard tab to explain what this is and point users to the About tab.

There appears to be a lot of code change, they're mostly due to indentation changes. I've really just grouped components that add custom columns and put them under `with gr.Box()`, and same for plotting components, so that they're more clearly separated in blocks.

### CODE REVIEW

**Comment by AmberLJC** [comment]
We should update 'About' section on the leaderboard github page as well.

**Comment by AmberLJC** [comment]
They also mention the visualization, I remember we had the default plot before, right?

**Comment by jaywonchung** [comment]
You mean the README in our repo?

**Comment by AmberLJC** [comment]
image
this one

**Comment by jaywonchung** [comment]
What's a good set of axes for the default plot? Perhaps as soon as we include energy, people will just stick to it. Then, maybe we can plot without energy, e.g. parameter vs truthfulqa, and tempt people to try plotting with energy.

**Comment by AmberLJC** [comment]
I think it's fine to let people stick to energy. people already know about para v.s. model performance

**Comment by jaywonchung** [comment]
Agreed. I'll go with params vs energy.

**Comment by AmberLJC** [comment]
actually, i prefer energy vs truthfulqa. as model performance is considered as most important.

**Comment by jaywonchung** [comment]
Model quality is not really represented by truthfulqa alone. It pretty much cannot be represented by anything. So I want to avoid having that as a default.

**Comment by AmberLJC** [comment]
make sense

**Comment by jaywonchung** [comment]
Updated. Can you take another look?

**Comment by AmberLJC** [comment]
It looks good! I will merge

**Pull request merged**
